### PR TITLE
Move instrumentation into ResourceController

### PR DESCRIPTION
**Pull request by sikachu**
Most of controllers in Spree::Backend actually inherited from Spree::Admin::ResourceController. By doing this, we will be able to instrument event from all admin backend controllers.

### CODE REVIEW

**Comment by vinniefranco** [comment]
:+1:

**Comment by sikachu** [comment]
@vinniefranco I actually submitted this PR prematurely. Can you take another look?

**Comment by vinniefranco** [comment]
Sure

On Tuesday, August 11, 2015, Prem Sichanugrist <notifications@github.com>
wrote:

> @vinniefranco <https://github.com/vinniefranco> I actually submitted this
> PR prematurely. Can you take another look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/groundctrl/proclaimer/pull/8#issuecomment-130037251>.
>


-- 
Vincent Franco

"Any intelligent fool can make things bigger and more complex... It takes a
touch of genius --- and a lot of courage to move in the opposite
direction."   -- Einstein

**Comment by vinniefranco** [comment]
:+1:

**Pull request merged**
